### PR TITLE
417 Do not stop all collections from importing when one fails

### LINKED ISSUE #417: If a Collection entry fails during Import, it halts the processing of all following Collection entries

### PR DESCRIPTION
**Pull request by bkiahstroud**
Closes #417 

Use `#perform_later` for collections that are not imported using the `collection_field_mapping`

### CODE REVIEW

**Review by sephirothkod — CHANGES_REQUESTED** [review]
This looks good for the most part, I would like to change that split so that it runs off of a set variable or defaults to :;| . since if a collection has a colon in the title (ex. "bobs collection: the beginning") it will always get split. Please add a todo or make a ticket for this.

Also there is a better way to do the depreciation, make it conditional with the line that call that specific key ie make it use the same unless statement so it only prints out when that key is called.

**Comment by bkiahstroud** [comment]
> I would like to change that split so that it runs off of a set variable or defaults to :;|

@sephirothkod there's [this ticket](https://github.com/samvera-labs/bulkrax/issues/213), does that still cover what you had in mind or should it be modified?

**Comment by sephirothkod** [comment]
That seems like it is referencing the field mappings, this isn't in the same area and so I am worried it would be missed. We should either create a new ticket for this or just add this specific location to the existing ticket (maybe start a checklist).

**Comment by bkiahstroud** [comment]
@sephirothkod how's this? https://github.com/samvera-labs/bulkrax/issues/429

**Comment by sephirothkod** [comment]
Looks good! Thanks!

**Review by sephirothkod — APPROVED** [review]

**Pull request merged**
