### PR TITLE
remove collection column on the importer and exporter show page

### PR DESCRIPTION
**Pull request by ShanaLMoore**
- [ ] remove collection column from exporter show pg

Screen Shot 2022-04-20 at 5 17 01 PM

- [ ] remove collection column from importers show pg per convo below and in slack

Screen Shot 2022-04-20 at 5 51 42 PM

### CODE REVIEW

**Review by bkiahstroud — APPROVED** [review]
Looks good to me 👍 

Should we also remove this column from the Exporter's show page as well?

**Review by alishaevn — APPROVED** [review]

**Comment by alishaevn** [comment]
> Looks good to me 👍
> 
> Should we also remove this column from the Exporter's show page as well?

@bkiahstroud do you mean importer page?

**Comment by ShanaLMoore** [comment]
removed from both importer and exporter pages

**Comment by ShanaLMoore** [comment]
removed from both importer and exporter pages cc @alishaevn @bkiahstroud

**Pull request merged**
